### ISSUE TITLE
let binding spec is incorrect

### ISSUE THREAD

**Issue by awstlaur** [brownplt/pyret-docs#14]
https://www.pyret.org/docs/latest/Declarations.html#%28elem._%28bnf-prod._%28.Pyret._let-decl%29%29%29

It currently is:
```
‹let-decl›: ‹binding› = ‹binop-expr›
```

I believe it should be:
```
‹let-decl›: ‹binding› = ‹expr›
```

**Comment by blerner** [comment]
It's correct, check the grammar file. Binop-expr is the more general expression form, actually.

**Comment by awstlaur** [comment]
Ah I missed that before! 
```
‹binop-expr›: ‹expr› (BINOP ‹expr›)*
```
The start (`*`) = _zero_ or more instances, so every `‹expr›` is indeed also a `‹binop-expr›`.

I was probably confused because I'm used to thinking of "expr" as referring to the most generic thing in a language.

Closing issue. Thanks!
