### ISSUE TITLE
gdrive imports are undocumented?

### ISSUE THREAD

**Issue by awstlaur** [brownplt/pyret-docs#15]
The only example on the relevant [docs page](http://www.pyret.org/docs/latest/Import_Statements.html) is `import equality as EQ` (a builtin library).

The `my-gdrive` and `shared-gdrive` variants should be documented there as well.

If they are documented elsewhere, I would not know where to look.

**Comment by blerner** [comment]
This is better documented now, in the Modules page of the horizon docs.
