### ISSUE TITLE
Possible Type in string-dict documentation

### ISSUE THREAD

**Issue by murrayLuke** [brownplt/pyret-docs#25]
Possible typo on the following line.

https://github.com/brownplt/pyret-docs/blob/3d9cf6f5a7bd73a51aa43a8d3d25db4071a4e980/src/trove/string-dict.scrbl#L249

Maybe this should return a mutable string dict?

The current line returns a String Dict (SD-of "a")
@collection-doc["mutable-string-dict" #:contract `(a-arrow ("elt" "a") ,(SD-of "a"))]

I think the correct line would be the following but I may be incorrect!

@collection-doc["mutable-string-dict" #:contract `(a-arrow ("elt" "a") ,(MSD-of "a"))]

**Comment by jpolitz** [comment]
Fixed, thanks!
