### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-docs#34]
Now that we have a glossary/index, searching seems more feasible. Adding a fuzzy-matching search textbox at the top of this page could go a long way:

https://www.pyret.org/docs/latest/Glossary.html

**Comment by jpolitz** [comment]
Hooray for incremental improvements! @blerner added the Glossary and then @sorawee made the search happen. Nice job making things better over time :-)

**Comment by blerner** [comment]
I think this is fixed and closed...
