### ISSUE TITLE
Searching for `include` in docs doesn't find anything

### ISSUE THREAD

**Issue by jbclements** [brownplt/pyret-docs#55]
First off, please feel free to close this issue; I'm partly just interested to know if this is the right way to report things like this, or if things like this should be reported at all.

I've just spent a happy half-hour running through some of the first assignments from csci0111, and in assignment 2 I can't use the link because I don't have a brown gmail address, no problem but I have to figure out how to import the list functions myself. Assignment 1 uses the form "include image" to import the image library.

Trying to use "include lists" fails with a giant list of "please don't re-import <foo>" errors. I went looking for "include" in the docs, and I'm pretty sure it's not there at all. I do see the docs for "import", which give me everything I need, but it looks like "include" is undocumented.

Steps to reproduce:

1) visit this URL: https://www.pyret.org/docs/latest/Glossary.html?q=include

**Comment by sorawee** [comment]
Here's a rendered version: https://www.pyret.org/docs/horizon/modules.html

**Comment by jbclements** [comment]
Okay, sounds good! Feel free to close this issue if you like.
